### ISSUE TITLE
filters not hiding in some cases

### ISSUE THREAD

**Issue by nickjohnford** [katydecorah/font-library#12]
Looks like the filter controls are hidden underneath the `header` when the gear icon is not toggled on.

Chrome on Mac at a width > 800px it works fine. Chrome with width < 800px the controls no longer have the `header` above them to hide under, so end up pushed over the tags.

Safari doesn't seem to hide the controls at all.

Firefox on mac acts like Chrome, except the controls seem taller than the `header`, so a small amount is still visible.

Possible untested fix: putting controls inside a container with `overflow: hidden`.

The new filters are great by the way!

**Comment by katydecorah** [comment]
Thanks for flagging @nickjohnford! That's what I get for writing code and watching the X-Files at the same time.

**Comment by nickjohnford** [comment]
:alien: :alien: :alien:
