### ISSUE TITLE
Feature Request: Typekit Support

### ISSUE THREAD

**Issue by MrPaulDriver** [katydecorah/font-library#14]
Great work. I'd love to see this extended to include Adobe Typekit who's font bowser is woefully inadequate.

**Comment by davelab6** [comment]
I think its nice to only list fonts that are libre licensed -- fonts allowing unlimited use by everyone

**Comment by MrPaulDriver** [comment]
I guess that is a fair point

**Comment by katydecorah** [comment]
Sorry for the delay in response @MrPaulDriver, thanks for your input. I was trying to think about how to make this work, but I agree with @davelab6.
