### ISSUE TITLE
Change dummy text when script filter changes

### ISSUE THREAD

**Issue by davelab6** [katydecorah/font-library#22]
Today: 

![screen shot 2015-06-24 at 11 18 50 pm](https://cloud.githubusercontent.com/assets/261579/8346212/671664aa-1ac7-11e5-9211-c54ce56e7bb0.png)

Tomorrow:

![screen shot 2015-06-24 at 11 20 18 pm](https://cloud.githubusercontent.com/assets/261579/8346232/99fb7f90-1ac7-11e5-80d1-f333265fdee4.png)

**Comment by davelab6** [comment]
Aha! You do this for Khmer :)

![screen shot 2015-06-25 at 12 46 50 am](https://cloud.githubusercontent.com/assets/261579/8347235/b10b3a20-1ad3-11e5-88e8-9cffe692e880.png)

**Comment by katydecorah** [comment]
Love this idea. And yeah! All the Khmer fonts only have one subset so I had to provide the correct language to avoid a 404 (and a couple Greek fonts, too).

**Comment by davelab6** [comment]
Right; the library should always contain a Latin, so that's a bug. https://github.com/google/fonts/issues/66
