### ISSUE TITLE
Custom Preview

### ISSUE THREAD

**Issue by MartinMuzatko** [katydecorah/font-library#41]
First of all - thank you for this brilliant library!
I'd love to have a custom preview to quickly show a custom text in the desired font. Other than that - great work so far!

**Comment by katydecorah** [comment]
@MartinMuzatko Thank you! And this is a feature that has crossed my mind, I'll work on implementing it 😊

**Comment by MartinMuzatko** [comment]
Awesome! Thank you for the quick reply. Google Fonts isn't quite as organized as this :D
